artifact_location: /home/vamsi/Desktop/my_projects/8.dvc_mlflow/Dvc-Mlflow-Pipeline/<your
  MLFLOW_TRACKING_URI>/0
creation_time: 1757520526670
experiment_id: '0'
last_update_time: 1757520526670
lifecycle_stage: active
name: Default
