name: train-validate-promote
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip show dvc

      - name: Sanity check DVC repo
        run: |
          source .venv/bin/activate
          pwd && ls -la
          test -f dvc.yaml
          dvc --version
          dvc root

      # Make sure your MLflow server is reachable from the runner:
      # Use a public URL, or switch to a self-hosted runner if it's private.
      - name: Export env (secrets)
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_MODEL_NAME:   ${{ secrets.MLFLOW_MODEL_NAME }}
          PROMOTE_MIN_ACCURACY: "0.92"
          PROMOTE_MIN_F1: "0.90"
          MODEL_API_RELOAD_URL: ${{ secrets.MODEL_API_RELOAD_URL }}
          MODEL_API_TOKEN:      ${{ secrets.MODEL_API_TOKEN }}
        run: |
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"
          echo "MLFLOW_MODEL_NAME=$MLFLOW_MODEL_NAME"
          echo "MODEL_API_RELOAD_URL=$MODEL_API_RELOAD_URL"

      - name: Reproduce DVC pipeline (force run)
        run: |
          source .venv/bin/activate
          dvc repro -f

      - name: Validate & maybe promote (sets alias & calls /reload)
        run: |
          source .venv/bin/activate
          python -m src.validate_and_promote
