# .github/workflows/train-validate-promote.yml
name: train-validate-promote
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: PROJECT_DIR    # <-- e.g. "mlflow/Dvc-Mlflow-Pipeline"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip show dvc

      - name: Sanity check DVC repo
        run: |
          source .venv/bin/activate
          pwd
          ls -la
          dvc --version
          dvc root           # should print PROJECT_DIR path

      - name: Export env (secrets)
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_MODEL_NAME:   ${{ secrets.MLFLOW_MODEL_NAME }}
          PROMOTE_MIN_ACCURACY: "0.92"
          PROMOTE_MIN_F1: "0.90"
          MODEL_API_RELOAD_URL: ${{ secrets.MODEL_API_RELOAD_URL }}
          MODEL_API_TOKEN:      ${{ secrets.MODEL_API_TOKEN }}
        run: |
          set -a
          echo "MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}"
          echo "MLFLOW_MODEL_NAME=${MLFLOW_MODEL_NAME}"
          echo "MODEL_API_RELOAD_URL=${MODEL_API_RELOAD_URL}"
          set +a

      - name: Reproduce DVC pipeline (force new run)
        run: |
          source .venv/bin/activate
          dvc repro -f

      - name: Validate & maybe promote (sets alias and calls /reload)
        run: |
          source .venv/bin/activate
          python -m src.validate_and_promote
