name: train-validate-promote
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  mlops:
    # Run on your self-hosted runner (configured on your laptop).
    # If you gave it a custom label like "mlops", include it here.
    runs-on: [self-hosted]
    timeout-minutes: 30
    env:
      # All values come from secrets (no hard-coded URIs/ports here)
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_MODEL_NAME: ${{ secrets.MLFLOW_MODEL_NAME }}
      MLFLOW_PRODUCTION_ALIAS: ${{ secrets.MLFLOW_PRODUCTION_ALIAS }}
      PROMOTE_MIN_ACCURACY: ${{ secrets.PROMOTE_MIN_ACCURACY }}
      PROMOTE_MIN_F1: ${{ secrets.PROMOTE_MIN_F1 }}
      MODEL_API_RELOAD_URL: ${{ secrets.MODEL_API_RELOAD_URL }}
      MODEL_API_TOKEN: ${{ secrets.MODEL_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check local services reachable (no secrets printed)
        run: |
          # MLflow
          code=$(curl -sS -o /dev/null -w "%{http_code}" "$MLFLOW_TRACKING_URI" || true)
          if [ "$code" = "000" ]; then
            echo "MLflow not reachable at $MLFLOW_TRACKING_URI"; exit 1
          else
            echo "MLflow HTTP: $code"
          fi
          # API health (optional) - only checks if URL is provided
          if [ -n "$MODEL_API_RELOAD_URL" ]; then
            base="${MODEL_API_RELOAD_URL%/reload}"
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$base/healthz" || true)
            echo "API /healthz HTTP: ${code:-000}"
          fi

      - name: Reproduce DVC pipeline (force run)
        run: |
          source .venv/bin/activate
          dvc repro -f

      - name: Validate & maybe promote (alias) and auto-/reload
        run: |
          source .venv/bin/activate
          python -m src.validate_and_promote

      - name: Upload logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: |
            logs
            dvc.lock
            metrics.json
