name: train-validate-promote
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # Point to the ephemeral MLflow server we will start in this job
      MLFLOW_TRACKING_URI: http://127.0.0.1:5000
      # Your project env
      MLFLOW_MODEL_NAME: iris-rf-classifier
      MLFLOW_PRODUCTION_ALIAS: production
      PROMOTE_MIN_ACCURACY: "0.92"
      PROMOTE_MIN_F1: "0.90"
      # Leave reload URL empty in CI unless you have a publicly reachable API
      MODEL_API_RELOAD_URL: ""
      MODEL_API_TOKEN: ""

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip show dvc mlflow

      - name: Sanity check DVC repo
        run: |
          source .venv/bin/activate
          pwd && ls -la
          test -f dvc.yaml
          dvc --version
          dvc root

      - name: Start MLflow server (ephemeral SQLite)
        run: |
          source .venv/bin/activate
          nohup mlflow server \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root ./mlruns \
            --host 127.0.0.1 --port 5000 > mlflow_server.log 2>&1 &
          python - <<'PY'
          import time, requests, sys
          for i in range(60):
              try:
                  r = requests.get("http://127.0.0.1:5000")
                  print("MLflow up:", r.status_code); sys.exit(0)
              except Exception as e:
                  time.sleep(1)
          raise SystemExit("MLflow did not start in time")
          PY

      - name: Reproduce DVC pipeline (force new run)
        run: |
          source .venv/bin/activate
          dvc repro -f

      - name: Validate & maybe promote (sets alias & tries /reload if configured)
        run: |
          source .venv/bin/activate
          python -m src.validate_and_promote

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-and-logs
          path: |
            mlruns
            mlflow_server.log
            logs
